import type { Service } from "@/lib/firestore/types";

export const staticServices: Service[] = [
  {
    id: "bending-services",
    title: "Bending Services",
    tagline: "Shaping Heavy Metal with Surgical Accuracy",
    description: "Our heavy-capacity bending operations handle everything from thin sheet profiles to 60mm-thick structural plate. Using servo-electric CNC press brakes with real-time angle feedback, we achieve repeatable precision on every bend — even on complex multi-stage jobs.",
    image: "/service-bending.png",
    features: ["Mild Steel Plate Bending", "Industrial SS Plate Bending", "Heavy Plate Bending", "Multi-Radius Profiles", "Back-Gauge CNC Control", "Tonnage up to 800T"],
    specs: [{ label: "Max Tonnage", value: "800T" }, { label: "Max Length", value: "6000mm" }, { label: "Accuracy", value: "±0.5°" }, { label: "Min Radius", value: "0.5T" }],
  },
  {
    id: "sheet-bending",
    title: "Sheet Bending Service",
    tagline: "Commercial Precision, Industrial Scale",
    description: "Precision sheet metal bending for automotive frames, HVAC enclosures, and commercial structures. Our fleet of press brakes handles both thin gauge sheets and medium-thickness plate, ensuring consistent geometry across high-volume production runs.",
    image: "/service-bending.png",
    features: ["Sheet Metal Bending", "Tipper Truck Components", "Laser Cutting & Bending", "Box & Pan Forming", "Automated Back Gauge", "Springback Compensation"],
    specs: [{ label: "Min Thickness", value: "0.5mm" }, { label: "Max Thickness", value: "25mm" }, { label: "Batch Size", value: "1–10,000+" }, { label: "Lead Time", value: "24–72 hrs" }],
  },
  {
    id: "steel-cutting",
    title: "Steel Cutting Services",
    tagline: "Clean Edges. Zero Compromise.",
    description: "High-speed shearing and cutting operations for thick industrial steel plates and sheets. From straight-line cuts on structural plate to complex profiling on CNC plasma, we deliver burr-free edges with minimal heat-affected zones.",
    image: "/service-steel-cutting.png",
    features: ["Stainless Steel Sheet Cutting", "Industrial Steel Plate Cutting", "Heavy Steel Cutting", "Plasma & Gas Cutting", "CNC Profiling", "Nesting Optimization"],
    specs: [{ label: "Max Thickness", value: "60mm MS" }, { label: "Max Sheet Size", value: "3000×12000mm" }, { label: "Squareness", value: "±0.3mm" }, { label: "Surface", value: "Burr-Free" }],
  },
  {
    id: "plate-bending",
    title: "Plate Bending & Rolling",
    tagline: "Cylinders, Cones & Curved Steel — Any Geometry",
    description: "Specialized plate rolling for tanks, pressure vessels, columns, and structural arches. Our 3-roll and 4-roll machines handle massive plate with exceptional roundness control, while our skilled operators manage the complex challenge of conical rolling.",
    image: "/service-plate-bending.png",
    features: ["Heavy Plate Rolling", "Cylinder Forming", "Cone Rolling", "Plate Pre-bending", "Structural Arches", "Vessel Shells"],
    specs: [{ label: "Max Plate Width", value: "3000mm" }, { label: "Max Thickness", value: "60mm" }, { label: "Min Diameter", value: "300mm" }, { label: "Ovality", value: "<1%" }],
  },
  {
    id: "laser-cutting",
    title: "CNC Laser Cutting",
    tagline: "±0.1mm Accuracy. Every. Single. Time.",
    description: "State-of-the-art fiber laser cutting systems delivering unmatched accuracy on intricate 2D profiles. With real-time kerf compensation, automatic nesting, and high-speed cutting heads, we process both simple blanks and highly complex geometries at production scale.",
    image: "/service-cnc.png",
    features: ["Mild Steel Laser Cutting", "Stainless Steel Cutting", "CNC Laser Profiles", "High-Speed Processing", "Complex Geometries", "Auto-Nesting for Savings"],
    specs: [{ label: "Tolerance", value: "±0.1mm" }, { label: "Max Thickness", value: "25mm MS" }, { label: "Bed Size", value: "3000×6000mm" }, { label: "Edge Quality", value: "Ra 3.2μm" }],
  },
  {
    id: "base-plate",
    title: "Base Plates & Fasteners",
    tagline: "The Foundation That Everything Else Stands On",
    description: "Heavy-duty base plates, anchor plates, and foundation bolts for structural and industrial installations. Machined to exact tolerances with precision drill patterns, our base plate systems ensure column bases, machinery mounts, and equipment foundations are rock-solid.",
    image: "/service-base-plates.png",
    features: ["MS Base Plates", "SS Base Plates", "Foundation Bolts", "Custom Structural Mounts", "Precision Drilled Holes", "Machined Bearing Surfaces"],
    specs: [{ label: "Max Size", value: "2000×2000mm" }, { label: "Max Thickness", value: "100mm" }, { label: "Hole Tolerance", value: "H7" }, { label: "Flatness", value: "±0.3mm/m" }],
  },
  {
    id: "profile-cutting",
    title: "Plate Profile Cutting",
    tagline: "Intricate Shapes from Thick Solid Plate",
    description: "Complex profile cutting from thick metal plate using CNC oxy-fuel and plasma systems. Whether you need flanges, frames, brackets, or custom structural shapes — our profiling machines handle thick plate with high edge quality and tight dimensional control.",
    image: "/service-profile.png",
    features: ["CNC Oxy-Fuel Profiling", "Plasma Profile Cutting", "Custom Shapes", "Thick Plate Processing", "High Edge Quality", "Batch Production"],
    specs: [{ label: "Max Thickness", value: "150mm (Oxy)" }, { label: "Plasma Thickness", value: "60mm" }, { label: "Positional Acc.", value: "±0.5mm" }, { label: "Min Feature", value: "5mm" }],
  },
  {
    id: "sheet-cutting",
    title: "Sheet Metal Cutting",
    tagline: "High Volume. Rapid Turnaround. Zero Waste.",
    description: "High-volume sheet metal shearing services for blanks, strips, and custom-size cuts. Our hydraulic guillotine shears deliver consistent squareness across large production batches, while advanced nesting software minimizes material waste.",
    image: "/service-steel-cutting.png",
    features: ["Precision Shearing", "High-Volume Production", "Minimal Material Waste", "Custom Blank Sizes", "Strip Cutting", "Rapid Delivery"],
    specs: [{ label: "Max Length", value: "4000mm" }, { label: "Max Thickness", value: "16mm" }, { label: "Squareness", value: "±0.2mm" }, { label: "Min Batch", value: "1 piece" }],
  },
];
