export const contactFaqs = [
  {
    question: "How fast can you deliver a quote?",
    answer:
      "We aim to provide quotes within 4 to 8 business hours for standard jobs. Send your DXF, DWG, STEP, IGES, or PDF drawings with material and thickness details for the fastest response.",
  },
  {
    question: "What file formats do you accept?",
    answer:
      "We accept DXF, DWG, STEP, IGES, PDF drawings, and sketch-based dimensions. Our engineers can also prepare CAD-based drawings from customer sketches.",
  },
  {
    question: "What materials and thicknesses do you handle?",
    answer:
      "We work with mild steel, galvanized sheet, and stainless steel sheet metal. We support sheet metal work from 1 mm up to 25 mm thickness and long-profile cutting and bending up to 10 meters.",
  },
  {
    question: "What are your main fabrication capabilities?",
    answer:
      "Our key services include sheet metal bending, shearing, CNC laser cutting, CNC plasma cutting, punching, rolling, fabrication, and plate profile cutting for industrial applications.",
  },
] as const;

export const siteConfig = {
  name: "Balaji Engineering Works",
  legalName: "Balaji Engineering Works",
  shortName: "Balaji Engineering",
  alternateName: "Balaji Engineering Works Sheet Metal Laser Cutting",
  alternateNames: [
    "Balaji Engineering Works",
    "Balaji Engineering",
    "Balaji Engineering Works Sheet Metal Laser Cutting",
  ],
  slogan: "Precision sheet metal forming, cutting, bending and fabrication in Surat",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://sheetmetallasercutting.com",
  liveBusinessSite: "https://www.balajiengineeringworks.in/",
  ogImage: "/opengraph-image",
  description:
    "Balaji Engineering Works is a Surat-based manufacturer and service provider of sheet metal bending, shearing, CNC laser cutting, CNC plasma cutting, punching, rolling, fabrication, and plate profile cutting services.",
  phone: "+91-7942957640",
  phoneDisplay: "+91 79429 57640",
  email: "info@balajiengineering.in",
  contactPerson: "Nikunj Sakariya",
  foundingDate: "2001",
  priceRange: "$$",
  gstNumber: "24BCUPS8314Q1ZK",
  businessType: "Manufacturer & Service Provider",
  legalStatusOfFirm: "Proprietorship",
  employeeRange: "11 to 25 People",
  annualTurnover: "5 - 25 Cr",
  locale: "en_IN",
  language: "en-IN",
  serviceAreas: ["Surat", "Gujarat", "Western India", "India"],
  industries: [
    "Sheet Metal Fabrication",
    "Sheet Metal Forming",
    "CNC Laser Cutting",
    "CNC Plasma Cutting",
    "Steel Plate Bending",
    "Plate Rolling",
    "Plate Profile Cutting",
    "Punching Works",
    "Heavy Fabrication",
    "Industrial Manufacturing",
  ],
  capabilities: [
    "Sheet metal work from 1 mm to 25 mm thickness",
    "Cutting and bending profiles up to 10 meter length",
    "Press brake capacity up to 1200 tonnes",
    "6 kW CNC fibre laser cutting",
    "Mild steel laser cutting up to 25 mm thickness",
    "Stainless steel laser cutting up to 16 mm thickness",
    "CNC plasma cutting services",
    "CAD drawing support from sketches",
  ],
  featuredClients: [
    "Reliance Jio Infocomm Limited",
    "Reliance Retail",
    "Western Railway",
    "Amazon",
    "L&T Construction",
    "L&T Hydrocarbon",
    "Suzlon Energy Limited",
    "Torrent Power Ltd.",
    "NTPC",
    "Gujarat Metro Rail Corporation Limited",
    "Mumbai Metro Rail Corporation Limited",
    "NHSRCL",
  ],
  keywords: [
    "sheet metal laser cutting",
    "sheet metal laser cutting Surat",
    "sheet metal bending Surat",
    "sheet metal fabrication Surat",
    "CNC laser cutting Surat",
    "CNC plasma cutting Surat",
    "plate bending services",
    "plate rolling services",
    "plate profile cutting service",
    "sheet metal forming works",
    "sheet metal punching works",
    "steel fabrication Gujarat",
    "heavy sheet metal work",
    "Balaji Engineering Works",
    "metal fabrication company India",
  ],
  address: {
    streetAddress:
      "Plot No. 11, 12, Soham Industrial Estate, NH 8 Kamrej, Opposite Hero Showroom",
    locality: "Navagam, Surat",
    region: "Gujarat",
    postalCode: "394185",
    country: "IN",
  },
  mapUrl:
    "https://maps.google.com/?q=Balaji+Engineering+Works+Plot+No.+11+12+Soham+Industrial+Estate+NH+8+Kamrej+Navagam+Surat+394185",
  sameAs: [
    "https://www.balajiengineeringworks.in/",
    "https://maps.google.com/?q=Balaji+Engineering+Works+Plot+No.+11+12+Soham+Industrial+Estate+NH+8+Kamrej+Navagam+Surat+394185",
  ],
} as const;
